name: MathEvent
version: 1.0.0B
api: [3.0.0]
main: Raphael\Math\Blaze
author: Raphael S.

# Feito por Raphael S. 
# Discord: https://www.blazehosting.com.br/discord
# https://github.com/Raphael1S/Math-Event
