CRIADOR: Raphael S. @ BlazeHosting


# Especifique o período de espera para que o plugin envie outra conta matemática se um jogador acertar a resposta e ninguém mais acertar.
Tempo: "5" # Medido em minutos.

# Decida se deseja conceder uma recompensa para quem acertar a conta matemática.
EconomyAPI: "sim" # Opções: sim ou não
Recompensa: "1000"

# A Chave do Plugin.
Chave: ""

# 17/04/2023
# 1.0.0B
 
