CRIADOR: Raphael S. @ BlazeHosting


# Especifique o período de espera para que o plugin envie outra conta matemática se um jogador acertar a resposta ou se ninguém mais acertar.
Tempo: "5" # Medido em minutos.

# Especifique se deseja conceder uma recompensa para quem acertar a conta matemática.
EconomyAPI: "sim" # Opções: sim ou não
Recompensa: "1000"

# Indique se você deseja habilitar o registro de logs no console para exibir o resultado e o vencedor.
# Se ativado, o resultado de uma nova conta será exibido no console assim que ela for iniciada.
Logs Console: "sim" # Opções: sim ou não

# A Chave do Plugin.
Chave: ""

# 17/04/2023
# 1.0.0B
 
